### ISSUE TITLE
Sharing common assets between repositories

### ISSUE THREAD

**Issue by avinashnxt** [harshal77/micro-frontend-multi-framework#2]
Hi Harshal,

How can we share common assets like some CSS files and images between projects?
Is it possible to have a common project that contains the common CSS files and images that can be shared between all the applications or do we have to have the files separately inside each application?

**Comment by harshal77** [comment]
Yes we can use the main common css and assets. We have to put all css and images in main container.Css will apply directly to childs. For assets or images we have to provide parent path
